### ISSUE TITLE
Instructions to install the library

### ISSUE THREAD

**Issue by SushilShrestha** [sushil79g/Nepali_nlp#30]
Hi guys, awesome repo. But the repo lacks installation instructions. also found the library on pip but the formatting of the instructions there is all messed up. Any plans for updating proper installation instructions ?

PS: do you guys accept contributions ? couldn't see the contributions document. 

PS: Used the tokenizer from the repo that was awesome. Kudos to the team. 🎉

**Comment by sushil79g** [comment]
we have updated the installation instruction in the README file. yes, we accept the contribution but we are currently bg with another project we will add a contribution document shortly.  for now, please go through README we will shortly reflect it on PyPi.
Thank you for the review

**Comment by SushilShrestha** [comment]
Looking forward to updates and best of luck 👍
