### ISSUE TITLE
Nepali_nlp module is not installing

### ISSUE THREAD

**Issue by prem-raj461** [sushil79g/Nepali_nlp#38]
it shows following error while trying to install as: "pip install Nepali-nlp".

ERROR: Could not find a version that satisfies the requirement Nepali-nlp
ERROR: No matching distribution found for Nepali-nlp

**Comment by sushil79g** [comment]
Did you check with steps in README
!pip install git+https://github.com/sushil79g/Nepali_nlp.git

Tried and working in my system (both window and Linux)

if you are comfortable with colab way, here is the playground link: 
https://colab.research.google.com/drive/1qkVsF72ncuTW3PYMAZ4wEpowkaaYtAZd?usp=sharing

let me know if the problem still persist

**Comment by sushil79g** [comment]
haven't heard you since then, closing this issue for now.
